#!/bin/sh
#
# blog - this script starts my blog as a daemon
#
# chkconfig: 23 86 14
# description: My blog is an HTTP server running on NodeJS.
# processname: blog
# config: /etc/sysconfig/blog
# pidfile: /var/run/blog.pid
#

# Source function library
. /etc/rc.d/init.d/functions

node="/usr/bin/node"
prog="blog"

# Source app configuration
[ -f "/etc/sysconfig/$prog" ] && . /etc/sysconfig/$prog

pidfile="/var/run/${prog}.pid"

start() {
    echo -n $"Starting $prog: "
    pushd /usr/share/blog > /dev/null
        daemon $node server.js > /var/log/blog/main.log 2>&1 &
	pid=$!
	echo "$pid" > $pidfile
	retval=$?
    popd > /dev/null
    echo
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    [ -f $pidfile ] && killproc -p $pidfile $prog
    retval=$?
    echo
    return $retval
}

case "$1" in
    start|stop)
        $1
        ;;
    restart)
        stop
        start
        ;;
    status)
        status $prog
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 2
esac
        
